# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('send_text', models.CharField(max_length=200)),
                ('send_time_utc', models.SmallIntegerField(null=True)),
                ('response_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.FloatField(null=True)),
                ('binary_value', models.SmallIntegerField(null=True)),
                ('text_value', models.CharField(max_length=1000, null=True)),
                ('response_collected', models.SmallIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('log_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_name', models.CharField(max_length=200)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_to_user', models.BooleanField()),
                ('message_type', models.SmallIntegerField()),
                ('text', models.CharField(max_length=200, null=True)),
                ('response_captured', models.BooleanField(default=False)),
                ('habit_in_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='NumericLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.FloatField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
                ('log_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogContext')),
            ],
        ),
        migrations.CreateModel(
            name='TextLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.CharField(max_length=1000)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
                ('log_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LogContext')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fbid', models.CharField(max_length=200)),
                ('state', models.SmallIntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('active_habit_entry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.HabitEntry')),
            ],
        ),
        migrations.AddField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
