# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fbid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('send_text', models.CharField(max_length=200)),
                ('send_time_utc', models.SmallIntegerField(null=True)),
                ('response_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.FloatField(null=True)),
                ('binary_value', models.BooleanField(default=False)),
                ('text_value', models.CharField(max_length=1000)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fbid', models.CharField(max_length=200)),
                ('state', models.SmallIntegerField()),
            ],
        ),
    ]
