# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goal_goalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Ben', max_length=200),
            preserve_default=False,
        ),
    ]
