# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_backgroundinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_habit_entry',
        ),
    ]
