# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160801_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='fbid',
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
