# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_active_habit_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinformation',
            name='current_home_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='current_work_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='ride_type_preference',
            field=models.SmallIntegerField(null=True),
        ),
    ]
