# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160801_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalentry',
            name='binary_value',
        ),
        migrations.AddField(
            model_name='goalentry',
            name='response_collected',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalentry',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 7, 45, 4, 996881)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='active_goal_entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GoalEntry'),
        ),
        migrations.AlterField(
            model_name='goalentry',
            name='text_value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
