# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160802_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalentry',
            name='binary_value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
