# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160807_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinformation',
            name='gender',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='locale',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='timezone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
