# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160808_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideshareInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lyft_access_token', models.CharField(max_length=100, null=True)),
                ('lyft_refresh_token', models.CharField(max_length=100, null=True)),
                ('ride_type_preference', models.CharField(max_length=100, null=True)),
                ('current_home_address', models.CharField(max_length=200, null=True)),
                ('current_work_address', models.CharField(max_length=200, null=True)),
                ('home_lat', models.FloatField(null=True)),
                ('home_long', models.FloatField(null=True)),
                ('work_lat', models.FloatField(null=True)),
                ('work_long', models.FloatField(null=True)),
                ('connected_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='backgroundinformation',
            name='current_home_address',
        ),
        migrations.RemoveField(
            model_name='backgroundinformation',
            name='current_work_address',
        ),
        migrations.RemoveField(
            model_name='backgroundinformation',
            name='ride_type_preference',
        ),
    ]
