# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_todotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_to_user', models.BooleanField()),
                ('message_type', models.SmallIntegerField()),
                ('goal_in_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
