# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160809_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshareinformation',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
