# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rideshareinformation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideshareinformation',
            old_name='connected_flag',
            new_name='lyft_connected_flag',
        ),
        migrations.AddField(
            model_name='rideshareinformation',
            name='uber_connected_flag',
            field=models.BooleanField(default=False),
        ),
    ]
