# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
