# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160809_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideshareinformation',
            old_name='home_long',
            new_name='home_lng',
        ),
        migrations.RenameField(
            model_name='rideshareinformation',
            old_name='work_long',
            new_name='work_lng',
        ),
    ]
