# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('log_type', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='PictureLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.FloatField(null=True)),
                ('binary_value', models.SmallIntegerField(null=True)),
                ('text_value', models.CharField(max_length=1000, null=True)),
                ('response_collected', models.SmallIntegerField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='response_captured',
            field=models.BooleanField(default=False),
        ),
    ]
