# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('log_type', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='LogContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_name', models.CharField(max_length=200)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
            ],
        ),
        migrations.CreateModel(
            name='NumericLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.FloatField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
                ('log_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogContext')),
            ],
        ),
        migrations.CreateModel(
            name='TextLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.CharField(max_length=1000)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
                ('log_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LogContext')),
            ],
        ),
    ]
