# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160809_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideshareinformation',
            name='lyft_access_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rideshareinformation',
            name='lyft_refresh_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
