# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_rideshareinformation_lyft_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshareinformation',
            name='send_ride_button_Flag',
            field=models.BooleanField(default=True),
        ),
    ]
