# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rideshareinformation_send_ride_button_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideshareinformation',
            old_name='send_ride_button_Flag',
            new_name='send_ride_button_flag',
        ),
    ]
