# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160813_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshareinformation',
            name='rideshare_service_preference',
            field=models.SmallIntegerField(default=0),
        ),
    ]
