# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rideshareinformation_rideshare_service_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField()),
                ('rideshare_service', models.SmallIntegerField()),
                ('ride_id', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('driver_first_name', models.CharField(max_length=200, null=True)),
                ('origin_address', models.CharField(max_length=200, null=True)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_address', models.CharField(max_length=200, null=True)),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('pickup_address', models.CharField(max_length=200, null=True)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=200, null=True)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('price', models.FloatField()),
                ('primetime_percentage', models.IntegerField(null=True)),
                ('rideshare_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RideshareInformation')),
            ],
        ),
    ]
