# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_ridehistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridehistoryitem',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='dest_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='dest_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='dropoff_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='dropoff_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='origin_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='origin_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='pickup_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='pickup_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ridehistoryitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
