# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160814_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numericlogentry',
            old_name='text_value',
            new_name='numeric_value',
        ),
    ]
