# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160814_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Log')),
                ('log_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogContext')),
            ],
        ),
    ]
