# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20160816_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlogentry',
            name='text_value',
            field=models.CharField(max_length=10000),
        ),
    ]
