# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20160902_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LogEntry')),
                ('requested_at', models.DateTimeField()),
                ('rideshare_service', models.SmallIntegerField()),
                ('ride_id', models.CharField(max_length=200)),
                ('ride_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('driver_first_name', models.CharField(max_length=200, null=True)),
                ('origin_address', models.CharField(max_length=200, null=True)),
                ('origin_lat', models.FloatField(null=True)),
                ('origin_lng', models.FloatField(null=True)),
                ('dest_address', models.CharField(max_length=200, null=True)),
                ('dest_lat', models.FloatField(null=True)),
                ('dest_lng', models.FloatField(null=True)),
                ('pickup_address', models.CharField(max_length=200, null=True)),
                ('pickup_lat', models.FloatField(null=True)),
                ('pickup_lng', models.FloatField(null=True)),
                ('dropoff_address', models.CharField(max_length=200, null=True)),
                ('dropoff_lat', models.FloatField(null=True)),
                ('dropoff_lng', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('primetime_percentage', models.IntegerField(null=True)),
            ],
            bases=('main.logentry',),
        ),
    ]
