# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_ridelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='ocurred_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 0, 29, 50, 526051)),
            preserve_default=False,
        ),
    ]
