# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_logentry_ocurred_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='ocurred_at',
            new_name='occurred_at',
        ),
    ]
