# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20160903_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foursquare_access_token',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foursquare_connected_flag',
            field=models.BooleanField(default=False),
        ),
    ]
