# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_locationlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_connected_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ridehistoryitem',
            name='rideshare_information',
        ),
        migrations.CreateModel(
            name='FoursquareConnection',
            fields=[
                ('thirdpartyconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ThirdPartyConnection')),
                ('access_token', models.CharField(max_length=1000, null=True)),
            ],
            bases=('main.thirdpartyconnection',),
        ),
        migrations.CreateModel(
            name='LyftConnection',
            fields=[
                ('thirdpartyconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ThirdPartyConnection')),
                ('refresh_token', models.CharField(max_length=1000, null=True)),
            ],
            bases=('main.thirdpartyconnection',),
        ),
        migrations.DeleteModel(
            name='RideHistoryItem',
        ),
    ]
