# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20160904_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyconnection',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
