# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_thirdpartyconnection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartyconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foursquare_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foursquare_connected_flag',
        ),
        migrations.AddField(
            model_name='foursquareconnection',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyftconnection',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
