# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20160904_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LogEntry')),
                ('source_type', models.SmallIntegerField()),
                ('foursquare_id', models.CharField(max_length=200, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('formatted_address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('img_url_prefix', models.CharField(max_length=200, null=True)),
                ('img_url_suffix', models.CharField(max_length=200, null=True)),
                ('img_dim_width', models.SmallIntegerField(null=True)),
                ('img_dim_height', models.SmallIntegerField(null=True)),
            ],
            bases=('main.logentry',),
        ),
        migrations.RemoveField(
            model_name='locationlogentry',
            name='logentry_ptr',
        ),
        migrations.DeleteModel(
            name='LocationLogEntry',
        ),
    ]
