# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_instagramconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='instagram_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='profile_picture',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramconnection',
            name='username',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
