# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20160908_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconnection',
            name='instagram_id',
            field=models.BigIntegerField(),
        ),
    ]
