# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20160908_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LogEntry')),
                ('instagram_id', models.CharField(max_length=100)),
                ('likes', models.SmallIntegerField()),
                ('link_to_post', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('thumbnail_height', models.SmallIntegerField()),
                ('thumbnail_width', models.SmallIntegerField()),
                ('low_res_url', models.CharField(max_length=200)),
                ('low_res_height', models.SmallIntegerField()),
                ('low_res_width', models.SmallIntegerField()),
                ('high_res_url', models.CharField(max_length=200)),
                ('high_res_height', models.SmallIntegerField()),
                ('high_res_width', models.SmallIntegerField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('location_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('location_street_address', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=1000, null=True)),
            ],
            bases=('main.logentry',),
        ),
    ]
