# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20160917_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideshareinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='user',
        ),
        migrations.DeleteModel(
            name='RideshareInformation',
        ),
        migrations.DeleteModel(
            name='ToDoTask',
        ),
    ]
