# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20160918_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dose',
        ),
        migrations.DeleteModel(
            name='GlucoseLog',
        ),
        migrations.DeleteModel(
            name='InsulinAmount',
        ),
    ]
