# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20160918_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='backgroundinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='BackgroundInformation',
        ),
    ]
