# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20160921_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='global_fbid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
