# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_profile_utc_offset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='profile',
        ),
    ]
