# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20160924_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_reminders_flag',
            field=models.BooleanField(default=True),
        ),
    ]
