# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_profile_send_reminders_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reminder_settings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
